//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movieapplication.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Movie
    {
        public int movieId { get; set; }
        public string movieName { get; set; }
        public string movieYear { get; set; }
        public string moviePlot { get; set; }
        public string moviePoster { get; set; }
        public Nullable<int> actorId { get; set; }
        public Nullable<int> producerId { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Producer Producer { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        [NotMapped]
        public IEnumerable<Actor> GetActorList { get; set; }
        [NotMapped]
        public string[] ActorList { get; set; }
    }
}
